# Знакомство с Pandas

Язык программирования Python стал популярен в научной среде и в частности, в области машинного обучения, из-за огромного количества качественных библиотек для работы с разнообразными данными. Две важные библиотеки, с которыми необходимо познакомиться до того, как переходить непосредственно к алгоритмам машинного обучения - это NumPy (https://numpy.org/) и Pandas (https://pandas.pydata.org/), которые составляют основу стека для работы с данными в Python.

В этом семинаре я буду пользоваться иллюстрациями из прекрасной вводной статьи по Pandas (рекомендую к просмотру для закрепления):

*   http://jalammar.github.io/gentle-visual-intro-to-data-analysis-python-pandas/

![Pandas logo](https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Pandas_logo.svg/1280px-Pandas_logo.svg.png)

Документация https://pandas.pydata.org/docs/user_guide/index.html

Библиотека Pandas представляет удобный способ организации табличных данных - объект `pandas.DataFrame`:

In [1]:
from pathlib import Path

import pandas as pd


# создадим небольшой CSV-файл на диске
tiny_dataset_path = Path("music.csv")
tiny_dataset_path.write_text(
    """
    Artist,Genre,Listeners,Plays\n
    Bille Holiday,Jazz,1300000,27000000\n
    Jimi Hendrix,Rock,2700000,70000000\n
    Miles Davis,Jazz,1500000,48000000\n
    SIA,Pop,2000000,74000000\n
    """
)

189

`pd.DataFrame` можно создать как из уже существующих матриц `np.array`, так и загрузив с диска. Поддерживается импорт большого набора форматов (csv, xlsx, json, parquet, feather, ...).

![excel to pandas](http://jalammar.github.io/images/pandas-intro/0%20excel-to-pandas.png)

In [2]:
df = pd.read_csv("music.csv")

In [3]:
df  # можно вывести всю таблицу на экран

              Artist Genre  Listeners     Plays
0      Bille Holiday  Jazz    1300000  27000000
1       Jimi Hendrix  Rock    2700000  70000000
2        Miles Davis  Jazz    1500000  48000000
3                SIA   Pop    2000000  74000000

In [4]:
df.head(2)  # можно вывести первые две записи

              Artist Genre  Listeners     Plays
0      Bille Holiday  Jazz    1300000  27000000
1       Jimi Hendrix  Rock    2700000  70000000

In [5]:
df.tail(1)  # или самую последнюю запись

      Artist Genre  Listeners     Plays
3        SIA   Pop    2000000  74000000

In [6]:
df.info()  # общая информация о колонках в датафрейме и их типах

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0       Artist  4 non-null      object
 1   Genre       4 non-null      object
 2   Listeners   4 non-null      int64
 3   Plays       4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 256.0+ bytes

### Выбор данных

![select column](http://jalammar.github.io/images/pandas-intro/2%20select-column.png)

![select rows](http://jalammar.github.io/images/pandas-intro/3%20select-rows.png)

![select column and rows](http://jalammar.github.io/images/pandas-intro/4%20select_column-and-rows.png)

### Фильтрация

![pandas filter 1](http://jalammar.github.io/images/pandas-intro/pandas-filter-1.png)

![filter](http://jalammar.github.io/images/pandas-intro/5%20filter.png)

### Группировка

![group by](http://jalammar.github.io/images/pandas-intro/8%20group-by.png)

### Создание новых колонок

![create new column](http://jalammar.github.io/images/pandas-intro/9%20create-new-column.png)

In [7]:
df["Genre"].value_counts()

Genre
Jazz    2
Rock    1
Pop     1
Name: count, dtype: int64

## Анализ датасета Титаник

In [8]:
!wget -O titanic.csv "https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv"

--2024-11-15 18:18:02--  https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv
Resolving web.stanford.edu (web.stanford.edu)... 171.67.215.200, 2607:f6d0:0:925a::ab43:d7c8
Connecting to web.stanford.edu (web.stanford.edu)|171.67.215.200|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 44225 (43K) [text/csv]
Saving to: ‘titanic.csv’

titanic.csv         100%[===================>]  43.19K  --.-KB/s    in 0.06s

2024-11-15 18:18:02 (732 KB/s) - ‘titanic.csv’ saved [44225/44225]

In [9]:
titanic_df = pd.read_csv("titanic.csv")

In [10]:
titanic_df

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
...,...,...,...,...,...,...,...,...
882,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.0000
883,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.0000
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.0000
886,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.7500

*Задание*
- *Сколько всего пассажиров погибло, а сколько выжило? В абсолютных числах и в %*
- *Как отличается средняя стоимость (fare) билета среди разных классов?*
- *Что вы можете сказать о средней выживаемости среди пассажиров разного класса?*
- *Что вы можете сказать о среднем возрасте среди группы выживших и погибших?*
- *Посчитайте среднюю выживаемость среди женщин и мужчин*
- *Сколько всего среди погибших было женщин? А сколько мужчин? А среди выживших?*
- *Рассмотрим отдельно группы детей (возраст < 18) и взрослых (> 18). Отличается ли выживаемость среди них?*
- *Сравните выживаемость женщин и мужчин среди детей и взрослых. Отличаются ли они?*

In [ ]:
# PUT YOUR CODE HERE